spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/tasks
    username: postgres
    password: 1234
#    hikari:
#      maximum-pool-size: 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
